[pytest]
pythonpath = .
addopts =
    --browser chromium
    --browser firefox
    --alluredir=allure-results
    --color=yes
    --junit-xml=test-results/results.xml
    --tracing=retain-on-failure
norecursedirs = teamcity_data teamcity_logs .git venv node_modules
markers =
    api: API tests
    ui: UI tests
    integration: Integration tests