imagePullPolicy: Always

webapp:
  image: jetbrains/teamcity-server:latest
  port: 8111
  storage:
    data: 5Gi
    logs: 1Gi

agent:
  image: jetbrains/teamcity-minimal-agent:latest

setup:
  image: glskill/teamcity-tests-version1:latest

tests:
  image: glskill/teamcity-tests-version1:latest
