
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamcity-agent
  labels:
    app: teamcity-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamcity-agent
  template:
    metadata:
      labels:
        app: teamcity-agent
    spec:
      containers:
        - name: teamcity-agent
          image: {{ .Values.agent.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            # Агент подключается к серверу по имени K8s Service (аналог docker network)
            - name: SERVER_URL
              value: "http://teamcity-server:{{ .Values.webapp.port }}"
